server:
  port: 8080
  
spring:
  application.name: spring-crud-h2
  
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
    
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect

  h2.console:
    enabled: true
    path: /h2-console