# my global config
global:
  scrape_interval:     5s  # By default, scrape targets every 15 seconds.
  evaluation_interval: 5s  
  scrape_timeout: 5s

# Discover targets from Eureka and scrape metrics from them (Whitebox monitoring)
scrape_configs:
- job_name: eureka-discovery
  eureka_sd_configs:
  - server: http://host.docker.internal:8761/eureka
    refresh_interval: 1s
  relabel_configs:
#  - source_labels: [__meta_eureka_app_name]
#    target_label: application
  - source_labels: [__meta_eureka_app_instance_metadata_metrics_path]
    target_label: __metrics_path__
  - source_labels: [__address__]
    target_label: instance
  - source_labels: [__meta_eureka_app_instance_metadata_application]
    target_label: application
  - source_labels: [__meta_eureka_app_instance_metadata_env]
    target_label: env
  - source_labels: [__meta_eureka_app_instance_metadata_version]
    target_label: version
