apiVersion: 1

# list of datasources that should be deleted from the database
deleteDatasources:
  - name: Prometheus
    orgId: 1

datasources:
- uid: prometheus
  orgId: 1
  name: Prometheus
  type: prometheus
  url: http://prometheus:9090 
  isDefault: true
  access: proxy
  readOnly: false
  editable: true
#  jsonData:
#    exemplarTraceIdDestinations:
#      - datasourceUid: tempo
#        name: trace_id
#    httpMethod: POST